name: Test Package

on: push

env:
  NODE_VERSION: 16

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: aboutbits/github-actions-node/setup-and-install@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test
